<?php

namespace ContainerIkdsIHT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XW6goeaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xW6goea' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xW6goea'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'presentationRepo' => ['privates', 'App\\Repository\\PresentationHomeRepository', 'getPresentationHomeRepositoryService', true],
            'repo' => ['privates', 'App\\Repository\\HomeRepository', 'getHomeRepositoryService', true],
        ], [
            'presentationRepo' => 'App\\Repository\\PresentationHomeRepository',
            'repo' => 'App\\Repository\\HomeRepository',
        ]);
    }
}
