<?php

namespace ContainerD7IslIe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_6Kf5PMiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.6Kf5PMi' shared service.
     *
     * @return \App\Controller\PresentationHomeRe
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\HomeController::index()": the $presentationRepo argument is type-hinted with the non-existent class or interface: "App\\Controller\\PresentationHomeRe". Did you forget to add a use statement?');
    }
}
