<?php

namespace ContainerD7IslIe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ALGyShNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ALGyShN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ALGyShN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'presentationRepo' => ['privates', '.errored.6Kf5PMi', NULL, 'Cannot determine controller argument for "App\\Controller\\HomeController::index()": the $presentationRepo argument is type-hinted with the non-existent class or interface: "App\\Controller\\PresentationHomeRe". Did you forget to add a use statement?'],
            'repo' => ['privates', 'App\\Repository\\HomeRepository', 'getHomeRepositoryService', true],
        ], [
            'presentationRepo' => '?',
            'repo' => 'App\\Repository\\HomeRepository',
        ]);
    }
}
