<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGUFeNLO\App_KernelLocalDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGUFeNLO/App_KernelLocalDebugContainer.php') {
    touch(__DIR__.'/ContainerGUFeNLO.legacy');

    return;
}

if (!\class_exists(App_KernelLocalDebugContainer::class, false)) {
    \class_alias(\ContainerGUFeNLO\App_KernelLocalDebugContainer::class, App_KernelLocalDebugContainer::class, false);
}

return new \ContainerGUFeNLO\App_KernelLocalDebugContainer([
    'container.build_hash' => 'GUFeNLO',
    'container.build_id' => '529918bd',
    'container.build_time' => 1598178287,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGUFeNLO');
