<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIkdsIHT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIkdsIHT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIkdsIHT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIkdsIHT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIkdsIHT\App_KernelDevDebugContainer([
    'container.build_hash' => 'IkdsIHT',
    'container.build_id' => '4b59909c',
    'container.build_time' => 1598203914,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIkdsIHT');
