<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUv2H4fE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUv2H4fE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUv2H4fE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUv2H4fE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUv2H4fE\App_KernelDevDebugContainer([
    'container.build_hash' => 'Uv2H4fE',
    'container.build_id' => 'e982638a',
    'container.build_time' => 1598185157,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUv2H4fE');
