<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUEtfQBW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUEtfQBW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUEtfQBW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUEtfQBW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUEtfQBW\App_KernelDevDebugContainer([
    'container.build_hash' => 'UEtfQBW',
    'container.build_id' => 'b8ccb1be',
    'container.build_time' => 1598556128,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUEtfQBW');
